---
- name: Update Google Chrome on Ubuntu
  hosts: your_target_hosts
  become: yes
  tasks:
    - name: Ensure wget is installed
      apt:
        name: wget
        state: present
        update_cache: yes

    - name: Download the latest Google Chrome .deb package
      get_url:
        url: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        dest: /tmp/google-chrome-stable_current_amd64.deb
        mode: '0644'

    - name: Install Google Chrome
      apt:
        deb: /tmp/google-chrome-stable_current_amd64.deb
        state: present

    - name: Clean up the downloaded package
      file:
        path: /tmp/google-chrome-stable_current_amd64.deb
        state: absent
